"""changed character starting level to pull from config

Revision ID: 094dedfeda72
Revises: 48c07ad1448d
Create Date: 2023-05-01 22:24:25.444139

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "094dedfeda72"
down_revision = "48c07ad1448d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
