"""user_ig is now account_id, character level now pulls from config, adjusted blockeduser columns

Revision ID: 1c1df7503576
Revises: 5eb5865b25e6
Create Date: 2023-05-04 03:40:56.483053

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "1c1df7503576"
down_revision = "5eb5865b25e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("chat_type", sa.Integer(), nullable=True),
        sa.Column("chat_index", sa.Integer(), nullable=True),
        sa.Column("sent_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("chatlog")
    with op.batch_alter_table("blocked_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blocked_by", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("character_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("nickname", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=True))
        batch_op.add_column(
            sa.Column(
                "character_class",
                sa.Enum(
                    "BARBARIAN", "BARD", "CLERIC", "FIGHTER", "RANGER", "ROGUE", "WIZARD", "NONE", name="characterclass"
                ),
                nullable=True,
            )
        )
        batch_op.drop_column("blocked_gender")
        batch_op.drop_column("blocked_character_class")
        batch_op.drop_column("blocked_nickname")
        batch_op.drop_column("blocked_character_id")
        batch_op.drop_column("blocked_account_id")
        batch_op.drop_column("blockee_character_id")

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=True))
        batch_op.drop_column("user_id")

    with op.batch_alter_table("hwids", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=True))
        batch_op.drop_column("user_id")

    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "inv_count", existing_type=sa.INTEGER(), nullable=True, existing_server_default=sa.text("'0'")
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.alter_column(
            "inv_count", existing_type=sa.INTEGER(), nullable=False, existing_server_default=sa.text("'0'")
        )

    with op.batch_alter_table("hwids", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=True))
        batch_op.drop_column("account_id")

    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.INTEGER(), nullable=True))
        batch_op.drop_column("account_id")

    with op.batch_alter_table("blocked_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blockee_character_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("blocked_account_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("blocked_character_id", sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column("blocked_nickname", sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column("blocked_character_class", sa.VARCHAR(length=9), nullable=True))
        batch_op.add_column(sa.Column("blocked_gender", sa.VARCHAR(length=6), nullable=True))
        batch_op.drop_column("character_class")
        batch_op.drop_column("gender")
        batch_op.drop_column("nickname")
        batch_op.drop_column("character_id")
        batch_op.drop_column("account_id")
        batch_op.drop_column("blocked_by")

    op.create_table(
        "chatlog",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("message", sa.VARCHAR(length=64), nullable=True),
        sa.Column("user_id", sa.VARCHAR(length=64), nullable=True),
        sa.Column("chat_type", sa.INTEGER(), nullable=True),
        sa.Column("chat_index", sa.INTEGER(), nullable=True),
        sa.Column("ts", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("chat_logs")
    # ### end Alembic commands ###
