"""Initial migration

Revision ID: 3316d022ea2c
Revises: 
Create Date: 2023-04-27 17:05:40.686110

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "3316d022ea2c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=20), nullable=False),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("secret_token", sa.String(length=21), nullable=True),
        sa.Column("created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column("ban_type", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("nickname", sa.String(length=20), nullable=True),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=True),
        sa.Column(
            "character_class",
            sa.Enum("BARBARIAN", "BARD", "CLERIC", "FIGHTER", "RANGER", "ROGUE", "WIZARD", name="characterclass"),
            nullable=True,
        ),
        sa.Column("created_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=True),
        sa.Column("experience", sa.Integer(), nullable=True),
        sa.Column("karma_rating", sa.Integer(), nullable=True),
        sa.Column("streaming_nickname", sa.String(length=15), nullable=True),
        sa.Column("perk0", sa.String(), nullable=True),
        sa.Column("perk1", sa.String(), nullable=True),
        sa.Column("perk2", sa.String(), nullable=True),
        sa.Column("perk3", sa.String(), nullable=True),
        sa.Column("skill0", sa.String(), nullable=True),
        sa.Column("skill1", sa.String(), nullable=True),
        sa.Column("spell0", sa.String(), nullable=True),
        sa.Column("spell1", sa.String(), nullable=True),
        sa.Column("spell2", sa.String(), nullable=True),
        sa.Column("spell3", sa.String(), nullable=True),
        sa.Column("spell4", sa.String(), nullable=True),
        sa.Column("spell5", sa.String(), nullable=True),
        sa.Column("spell6", sa.String(), nullable=True),
        sa.Column("spell7", sa.String(), nullable=True),
        sa.Column("spell8", sa.String(), nullable=True),
        sa.Column("spell9", sa.String(), nullable=True),
        sa.Column("ranking_coin", sa.Integer(), nullable=True),
        sa.Column("ranking_kill", sa.Integer(), nullable=True),
        sa.Column("ranking_escape", sa.Integer(), nullable=True),
        sa.Column("ranking_adventure", sa.Integer(), nullable=True),
        sa.Column("ranking_lich", sa.Integer(), nullable=True),
        sa.Column("ranking_ghostking", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("nickname"),
    )
    op.create_table(
        "hwids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("hwid", sa.String(length=64), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=True),
        sa.Column("seen_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hwid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hwids")
    op.drop_table("characters")
    op.drop_table("accounts")
    # ### end Alembic commands ###
