"""added merchants to the database

Revision ID: 422a4c93bed7
Revises: 1c1df7503576
Create Date: 2023-05-09 11:29:20.337951

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "422a4c93bed7"
down_revision = "1c1df7503576"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=True),
        sa.Column(
            "merchant",
            sa.Enum(
                "SURGEON",
                "SANTA",
                "WOODSMAN",
                "TAILOR",
                "TREASURER",
                "LEATHERSMITH",
                "ARMOURER",
                "THECOLLECTOR",
                "ALCHEMIST",
                "TAVERNMASTER",
                "WEAPONSMITH",
                "GOBLINMERCHANT",
                "VALENTINE",
                "PUMPKINMAN",
                name="merchantclass",
            ),
            nullable=True,
        ),
        sa.Column("refresh_time", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("merchant_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("remaining", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("index", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_column("index")
        batch_op.drop_column("remaining")
        batch_op.drop_column("merchant_id")

    op.drop_table("merchants")
    # ### end Alembic commands ###
