"""Added merchants to the database

Revision ID: 43904c40d763
Revises: 1c1df7503576
Create Date: 2023-05-07 17:09:16.674391

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision = '43904c40d763'
down_revision = '1c1df7503576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_item_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('primary', sa.Boolean(), nullable=True),
    sa.Column('property', sa.String(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('ammo_count', sa.Integer(), nullable=True),
    sa.Column('inv_count', sa.Integer(), nullable=True),
    sa.Column('remaining', sa.Integer(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('merchant', sa.Enum('SURGEON', 'SANTA', 'WOODSMAN', 'TAILOR', 'TREASURER', 'LEATHERSMITH', 'ARMOURER', 'THECOLLECTOR', 'ALCHEMIST', 'TAVERNMASTER', 'WEAPONSMITH', 'GOBLINMERCHANT', 'VALENTINE', 'PUMPKINMAN', name='merchantclass'), nullable=True),
    sa.Column('refresh_time', sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merchants')
    op.drop_table('merchant_items')
    op.drop_table('merchant_item_attributes')
    # ### end Alembic commands ###
