"""Renamed user_id to account_id across the models

Revision ID: 555a5ce93305
Revises: 094dedfeda72
Create Date: 2023-05-01 23:02:17.447196

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "555a5ce93305"
down_revision = "094dedfeda72"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("characters", sa.Column("account_id", sa.Integer(), nullable=True))
    op.drop_column("characters", "user_id")
    op.add_column("hwids", sa.Column("account_id", sa.Integer(), nullable=True))
    op.drop_column("hwids", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hwids", sa.Column("user_id", sa.INTEGER(), nullable=True))
    op.drop_column("hwids", "account_id")
    op.add_column("characters", sa.Column("user_id", sa.INTEGER(), nullable=True))
    op.drop_column("characters", "account_id")
    # ### end Alembic commands ###
