"""Added flag for if the user is a trader

Revision ID: 5f041eb74995
Revises: b53c793562c7
Create Date: 2023-05-16 21:27:28.795934

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "5f041eb74995"
down_revision = "b53c793562c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_trader", sa.Boolean(), nullable=True, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_column("is_trader")

    # ### end Alembic commands ###
