"""added blocked user support

Revision ID: 62baba80a478
Revises: e8da5956d6a3
Create Date: 2023-04-29 06:16:35.001563

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "62baba80a478"
down_revision = "e8da5956d6a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blocked_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("blockee_character_id", sa.Integer(), nullable=True),
        sa.Column("blocked_account_id", sa.Integer(), nullable=True),
        sa.Column("blocked_character_id", sa.Integer(), nullable=True),
        sa.Column("blocked_nickname", sa.String(length=20), nullable=True),
        sa.Column("blocked_gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=True),
        sa.Column(
            "blocked_character_class",
            sa.Enum(
                "BARBARIAN", "BARD", "CLERIC", "FIGHTER", "RANGER", "ROGUE", "WIZARD", "NONE", name="characterclass"
            ),
            nullable=True,
        ),
        sa.Column("blocked_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("blocked_users")
    # ### end Alembic commands ###
