"""Added inventory count

Revision ID: 666ee8c39e0e
Revises: dabc974f380f
Create Date: 2023-04-30 02:04:10.027857

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "666ee8c39e0e"
down_revision = "dabc974f380f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("inv_count", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "inv_count")
    # ### end Alembic commands ###
