"""modified hwids table

Revision ID: 73c5909eb073
Revises: b53c793562c7
Create Date: 2023-05-16 18:47:35.075991

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "73c5909eb073"
down_revision = "b53c793562c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hwids")
    op.create_table(
        "hwids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("hwid", sa.String(length=64), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=True),
        sa.Column("seen_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hwids")
    op.create_table(
        "hwids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("hwid", sa.String(length=64), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=True),
        sa.Column("seen_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hwid"),
    )
    # ### end Alembic commands ###
