"""Added IPAddress Table

Revision ID: c3555b3a5332
Revises: b53c793562c7
Create Date: 2023-05-16 18:59:05.677516

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "c3555b3a5332"
down_revision = "b53c793562c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ip_addresses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(length=45), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ip_addresses")
    # ### end Alembic commands ###
