"""ChatLog user_id is now account_id

Revision ID: d8b86af1a161
Revises: dd570a52541a
Create Date: 2023-05-02 02:37:39.000201

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "d8b86af1a161"
down_revision = "dd570a52541a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("chat_type", sa.Integer(), nullable=True),
        sa.Column("chat_index", sa.Integer(), nullable=True),
        sa.Column("sent_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("chatlog")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatlog",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("message", sa.VARCHAR(length=64), nullable=False),
        sa.Column("chat_type", sa.INTEGER(), nullable=False),
        sa.Column("chat_index", sa.INTEGER(), nullable=False),
        sa.Column("ts", sa.DATETIME(), nullable=False),
        sa.Column("account_id", sa.VARCHAR(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("chat_logs")
    # ### end Alembic commands ###
