"""Added chatlog table

Revision ID: dabc974f380f
Revises: 07685a4b5061
Create Date: 2023-04-29 11:36:30.553202

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "dabc974f380f"
down_revision = "e8da5956d6a3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chatlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message", sa.String(length=64), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("chat_type", sa.Integer(), nullable=True),
        sa.Column("chat_index", sa.Integer(), nullable=True),
        sa.Column("ts", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chatlog")
    # ### end Alembic commands ###
