"""Added inventory count

Revision ID: e80361e4431e
Revises: 07685a4b5061
Create Date: 2023-04-29 16:25:56.044312

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "e80361e4431e"
down_revision = "07685a4b5061"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("items", sa.Column("inv_count", sa.Integer(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("items", "inv_count")
    # ### end Alembic commands ###
