# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: InGame.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dndserver.protos import _Character_pb2 as __Character__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cInGame.proto\x12\tDC.Packet\x1a\x10_Character.proto\"\xa1\x01\n\x1aSS2C_ENTER_GAME_SERVER_NOT\x12\x0c\n\x04port\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x11\n\tsessionId\x18\x03 \x01(\t\x12\x11\n\taccountId\x18\x04 \x01(\t\x12\x13\n\x0bisReconnect\x18\x05 \x01(\r\x12.\n\x08nickName\x18\x06 \x01(\x0b\x32\x1c.DC.Packet.SACCOUNT_NICKNAME\"{\n\x17SC2S_AUTO_MATCH_REG_REQ\x12\x0c\n\x04mode\x18\x01 \x01(\r\x12\x0e\n\x06region\x18\x02 \x01(\r\x12\x16\n\x0e\x64ifficultyType\x18\x03 \x01(\r\"*\n\x04MODE\x12\x08\n\x04NONE\x10\x00\x12\x0c\n\x08REGISTER\x10\x01\x12\n\n\x06\x43\x41NCEL\x10\x02\"\x8c\x02\n\x17SS2C_AUTO_MATCH_REG_RES\x12\x0e\n\x06result\x18\x01 \x01(\r\"\xe0\x01\n\x06RESULT\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02\x12\x17\n\x13\x46\x41IL_ALREADY_TRYING\x10\x03\x12\x1e\n\x1a\x46\x41IL_NO_READY_PARTY_MEMBER\x10\x04\x12\x16\n\x12\x46\x41IL_REGION_SELECT\x10\x05\x12\x17\n\x13\x46\x41IL_SERVER_DISABLE\x10\x06\x12\x1e\n\x1a\x46\x41IL_SHORTAGE_ENTRANCE_FEE\x10\x07\x12\x12\n\x0e\x46\x41IL_SOLO_ONLY\x10\x08\x12\x17\n\x13\x46\x41IL_SHORTAGE_LEVEL\x10\t\"1\n\x1cSC2S_GAME_ENTER_COMPLETE_NOT\x12\x11\n\tisSuccess\x18\x01 \x01(\r\"<\n\x1cSS2C_AUTO_MATCH_REG_TEAM_NOT\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x0c\n\x04mode\x18\x02 \x01(\r\"^\n\x19SC2S_RECONNECT_INGAME_REQ\x12\x11\n\tisRefusal\x18\x01 \x01(\r\x12.\n\x08nickName\x18\x02 \x01(\x0b\x32\x1c.DC.Packet.SACCOUNT_NICKNAME\"?\n\x19SS2C_RECONNECT_INGAME_RES\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x12\n\nserviceUrl\x18\x02 \x01(\t\"H\n\x19SS2C_FLOOR_MATCHMAKED_NOT\x12\x0c\n\x04port\x18\x01 \x01(\r\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x11\n\tsessionId\x18\x03 \x01(\tB\x1e\n\x12\x63om.packets.ingameB\x06ingameP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'InGame_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\022com.packets.ingameB\006ingameP\000'
  _globals['_SS2C_ENTER_GAME_SERVER_NOT']._serialized_start=46
  _globals['_SS2C_ENTER_GAME_SERVER_NOT']._serialized_end=207
  _globals['_SC2S_AUTO_MATCH_REG_REQ']._serialized_start=209
  _globals['_SC2S_AUTO_MATCH_REG_REQ']._serialized_end=332
  _globals['_SC2S_AUTO_MATCH_REG_REQ_MODE']._serialized_start=290
  _globals['_SC2S_AUTO_MATCH_REG_REQ_MODE']._serialized_end=332
  _globals['_SS2C_AUTO_MATCH_REG_RES']._serialized_start=335
  _globals['_SS2C_AUTO_MATCH_REG_RES']._serialized_end=603
  _globals['_SS2C_AUTO_MATCH_REG_RES_RESULT']._serialized_start=379
  _globals['_SS2C_AUTO_MATCH_REG_RES_RESULT']._serialized_end=603
  _globals['_SC2S_GAME_ENTER_COMPLETE_NOT']._serialized_start=605
  _globals['_SC2S_GAME_ENTER_COMPLETE_NOT']._serialized_end=654
  _globals['_SS2C_AUTO_MATCH_REG_TEAM_NOT']._serialized_start=656
  _globals['_SS2C_AUTO_MATCH_REG_TEAM_NOT']._serialized_end=716
  _globals['_SC2S_RECONNECT_INGAME_REQ']._serialized_start=718
  _globals['_SC2S_RECONNECT_INGAME_REQ']._serialized_end=812
  _globals['_SS2C_RECONNECT_INGAME_RES']._serialized_start=814
  _globals['_SS2C_RECONNECT_INGAME_RES']._serialized_end=877
  _globals['_SS2C_FLOOR_MATCHMAKED_NOT']._serialized_start=879
  _globals['_SS2C_FLOOR_MATCHMAKED_NOT']._serialized_end=951
# @@protoc_insertion_point(module_scope)
