# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IronMace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eIronMace.proto\x12\tDC.Packet\"3\n\x0eIronMace_Login\x12\x0f\n\x07loginId\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x9f\x01\n\x12IronMace_Login_Res\x12\x0e\n\x06result\x18\x01 \x01(\r\x12\x14\n\x0c\x65rrorMessage\x18\x02 \x01(\t\"c\n\x15IronMace_Login_Result\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x1a\n\x16\x46\x41IL_NOT_FOUND_ACCOUNT\x10\x64\x12\x17\n\x13\x46\x41IL_WRONG_PASSWORD\x10\x65\"3\n\x0eIronMace_Token\x12\x0f\n\x07loginId\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"#\n\x12IronMace_Token_Res\x12\r\n\x05token\x18\x02 \x01(\tB\"\n\x14\x63om.packets.ironMaceB\x08IronMaceP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'IronMace_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024com.packets.ironMaceB\010IronMaceP\000'
  _globals['_IRONMACE_LOGIN']._serialized_start=29
  _globals['_IRONMACE_LOGIN']._serialized_end=80
  _globals['_IRONMACE_LOGIN_RES']._serialized_start=83
  _globals['_IRONMACE_LOGIN_RES']._serialized_end=242
  _globals['_IRONMACE_LOGIN_RES_IRONMACE_LOGIN_RESULT']._serialized_start=143
  _globals['_IRONMACE_LOGIN_RES_IRONMACE_LOGIN_RESULT']._serialized_end=242
  _globals['_IRONMACE_TOKEN']._serialized_start=244
  _globals['_IRONMACE_TOKEN']._serialized_end=295
  _globals['_IRONMACE_TOKEN_RES']._serialized_start=297
  _globals['_IRONMACE_TOKEN_RES']._serialized_end=332
# @@protoc_insertion_point(module_scope)
