from enum import Enum

class BanType(Enum):
    FAIL_LOGIN_BAN_USER = 12
    FAIL_LOGIN_BAN_USER_CHEATER = 13
    FAIL_LOGIN_BAN_USER_INAPPROPRIATE_NAME = 14
    FAIL_LOGIN_BAN_USER_ETC = 15
    FAIL_LOGIN_BAN_HARDWARE = 16