name: Flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
    
    - name: Setup poetry
      uses: abatilo/actions-poetry@v2
    
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
      
    - name: Install dependencies
      run: poetry install

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
