"""Modified HWIDs Table, hwid is not more unique

Revision ID: ce81c90ea56b
Revises: 64412c0be1f7
Create Date: 2023-05-11 21:34:00.622417

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "ce81c90ea56b"
down_revision = "64412c0be1f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hwids")
    op.create_table(
        "hwids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("hwid", sa.String(length=64), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=True),
        sa.Column("seen_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hwids")
    op.create_table(
        "hwids",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.Column("hwid", sa.String(length=64), nullable=True),
        sa.Column("is_banned", sa.Boolean(), nullable=True),
        sa.Column("seen_at", sqlalchemy_utils.types.arrow.ArrowType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hwid"),
    )
    # ### end Alembic commands ###
