"""added IPAddress Table

Revision ID: da3ce2b00c91
Revises: 64412c0be1f7
Create Date: 2023-05-11 16:26:33.766461

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "da3ce2b00c91"
down_revision = "64412c0be1f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ip_addresses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(length=45), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ip_addresses")
    # ### end Alembic commands ###
